### PR TITLE
Adding CheckPeriod property for both Host & Service objects

### PR DESCRIPTION
**Pull request by AmitBenAmi**
We're using the CheckPeriod property, hence adding them to both objects: Host/Service

### CODE REVIEW

**Comment by mhutter** [comment]
@simu should those be `omitempty`?

**Comment by simu** [comment]
Yeah, since `check_period` is marked as optional in the documentation (cf. https://icinga.com/docs/icinga2/latest/doc/09-object-types/#host for the Host object), it's a good idea to make them `omitempty`, to avoid surprises when the field isn't set.

**Comment by AmitBenAmi** [comment]
@mhutter @simu I changed the json parameters and added `omitempty` as required like the other fields that are optional.

**Review by simu — APPROVED** [review]

**Comment by simu** [comment]
LGTM, thanks for the contribution

**Pull request merged**
